name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish_pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Build
      run: make build
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: make publish

  publish_docker_hub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: 2gistestlabs
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 2gistestlabs/fresh-deps:latest,2gistestlabs/fresh-deps:${{ env.RELEASE_VERSION }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
